### ISSUE TITLE
Support @extschema:name@ syntax

### ISSUE THREAD

**Issue by jgpruitt** [timescale/pgspot#180]
In postgres 16+, you can use `@extschema:name@` in extension SQL code to refer to the schema in which another extension resides.

https://www.postgresql.org/docs/current/extend-extensions.html#EXTEND-EXTENSIONS-RELOCATION

>If an extension references objects belonging to another extension, it is recommended to schema-qualify those references. To do that, write @extschema:name@ in the extension's script file, where name is the name of the other extension (which must be listed in this extension's requires list). This string will be replaced by the name (double-quoted if necessary) of that extension's target schema.

Currently, pgspot does not understand this syntax:

```bash
pgspot myextension--0.1.0.sql 

 Errors: 0 Warnings: 0 Unknown: 0 
 syntax error at or near "@", at index 3631
```

**Comment by jgpruitt** [comment]
Actually, this looks like it is an issue with pglast. 

```python3
from pglast import parse_sql
root = parse_sql("""
create function @extschema@.my_extension_function() returns int
as $func$
return 42
$func$
language plpython3u strict volatile parallel safe security invoker
set search_path to pg_catalog, pg_temp
;
""")
print(root)
```

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pglast/parser.pyx", line 278, in pglast.parser.parse_sql
pglast.parser.ParseError: syntax error at or near "@", at index 17
```
